version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Installing kubectl"
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - pwd
      - ls -las
      - mv ./kubectl /usr/local/bin/kubectl
      - echo "Installing helm"
      - wget https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
      - chmod +x ./linux-amd64/helm
      - mv ./linux-amd64/helm /usr/local/bin/helm
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Creating helm package
      - helm init -c
      - helm repo add upp http://k8s-pipeline-lib-helm-repo-test2.s3-website-eu-west-1.amazonaws.com
      - helm package --version 0.0.1 helm/$IMAGE_REPO_NAME
      - helm repo index --merge $HELM_HOME/.helm/repository/cache/upp-index.yaml --url http://k8s-pipeline-lib-helm-repo-test2.s3-website-eu-west-1.amazonaws.com .
      - cat $HELM_HOME/.helm/repository/cache/upp-index.yaml
      - aws s3 cp ./$IMAGE_REPO_NAME-0.0.1.tgz s3://k8s-pipeline-lib-helm-repo-test2/
      - mkdir /target
      - mv ./$IMAGE_REPO_NAME-0.0.1.tgz /target/
      - echo "0.0.1" > /target/VERSION
      - echo $IMAGE_REPO_NAME > /target/REPO_NAME

artifacts:
  files:
    - /target/$IMAGE_REPO_NAME-0.0.1.tgz
    - /target/VERSION
    - /target/REPO_NAME
  discard-paths: yes
